cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("add-product-to-cart/", views.add_product_to_cart,
         name="add_product_to_cart"),
    path("remove-product-from-cart/", views.remove_product_from_cart,
         name="remove_product_from_cart"),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index")
]

product/urls.py
from django.urls import path, re_path

from product.views import (
    product_list,
    product_list_filter,
    ProductDetailView,
    like_product,
    remove_comment,
    change_comment_status,
)

app_name = "product"

urlpatterns = [
    path("", product_list, name="list"),
    path("filter/", product_list_filter, name="filter"),
    path("like-product/", like_product, name="like_product"),
    path("remove-comment/", remove_comment, name="remove_coment"),
    path("change-comment-status/", change_comment_status, name="change_comment-status"),
    re_path(r"(?P<slug>[-\w0-9]+)/$", ProductDetailView.as_view(), name="detail"),
]

shop_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('account.urls')),
    path('products/', include('product.urls')),
    path('user/', include('user_panel.urls')),
    path('cart/', include('cart.urls')),
    path('contact-us/', include('contact_us.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_panel/urls.py
from django.urls import path

from . import views


app_name = 'user_panel'

urlpatterns = [
    path("", views.DashboardView.as_view(), name="dashboard"),

    # edit profile
    path("edit-profile/", views.EditProfileView.as_view(), name="edit_profile"),
    path("change-password/", views.change_password, name="change_password"),

    # product list
    path("lists/", views.lists, name="lists"),
    path("lists/create-list/", views.create_list, name="create_list"),
    path("lists/edit-list/", views.edit_list, name="edit_list"),
    path("lists/remove-list/", views.remove_list, name="remove_list"),
    path("lists/add-product-to-list/",
         views.add_product_to_list, name="add_product_to_list"),
    path("lists/remove-product-from-list/",
         views.remove_product_from_list, name="remove_product_from_list"),
    path("lists/filter/", views.products_list_filter, name="filter"),
    path("lists/<str:list_title>/", views.list_detail, name="list_detail"),

    # cart
    path("cart/", views.cart, name="cart"),

    # order
    path("orders/", views.orders, name="orders"),
    path("orders/<int:order_id>", views.order_detail, name="order_detail")
]

user_panel/models.py
from django.db import models


class UserProductList(models.Model):
    title = models.CharField(max_length=75, verbose_name="عنوان")
    description = models.TextField(
        blank=True, null=True, verbose_name="توضیحات")
    user = models.ForeignKey(
        to="account.User", on_delete=models.CASCADE, related_name="product_lists", verbose_name="کاربر")
    products = models.ManyToManyField(
        to="product.Product", related_name="user_lists", blank=True, verbose_name="محصولات")

    def __str__(self) -> str:
        return f"{self.user.username}-{self.title}"

    class Meta:
        unique_together = [
            ("user", "title")
        ]
        verbose_name = "لیست محصولات کاربران"
        verbose_name_plural = "لیست های محصولات کاربران"

cart/views.py
from django.http import JsonResponse
from django.views.decorators.http import require_GET
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string

from product.models import Product, ProductColorVariant
from .models import Cart, CartItem


@require_GET
@login_required
def add_product_to_cart(request):
    # Get product color variant id, base product id and quantity.
    try:
        id = int(request.GET.get("id"))
        base_product_id = int(request.GET.get("base_product_id"))
        quantity = int(request.GET.get("quantity", 1))
    # If the entered data is not numeric return error.
    except:
        response = {"text": "مقداری نامعتبر وارد شده است",
                    "icon": "error", "position": "center"}
        return JsonResponse(response)

    # Find product.
    product = ProductColorVariant.objects.filter(
        product__is_enable=True, id=id).first()
    # If the product is not found, return error.
    if product is None:
        base_product = Product.enabled.filter(id=base_product_id).first()
        if base_product is not None and not base_product.stock_count:
            response = {"text": "در انبار موجود نمی باشد", "icon": "error",
                        "position": "center"}
        else:
            response = {"text": "محصولی یافت نشد", "icon": "error",
                        "position": "center"}
        return JsonResponse(response)
    # Validate the entered quantity.
    if quantity < 1 or quantity > product.stock_count:
        response = {"text": "تعداد وارد شده نامعتبر است",
                    "icon": "error", "position": "center"}
        return JsonResponse(response)

    user = request.user

    # Get the user's open cart if it exists, otherwise create it and then get it.
    cart, _ = Cart.objects.get_or_create(user=user, is_paid=False)

    # Get the current product cart-item if it exists, otherwise
    # create it and then get it.
    cart_item, created = CartItem.objects.get_or_create(
        cart=cart, product=product, defaults={"quantity": quantity})

    if created:
        response = {"text": "محصول با موفقیت به سبد خرید شما افزوده شد",
                    "icon": "success", "position": "center"}
    else:
        # Save the changes.
        cart_item.quantity = quantity
        cart_item.save()

        response = {"text": "تعداد محصول در سبد خرید با موفقیت تغییر یافت",
                    "icon": "success", "position": "center",
                    "cart_item_total_price": cart_item.total_price(),
                    "cart_total_discounted_price": cart.total_discounted_price(),
                    "cart_total_discounted": cart.total_discounted(),
                    "cart_total_price": cart.total_price()}

    # Render the product colors area for update the item quantities.
    colors = product.product.in_stock_color_variants()
    product_colors_area = render_to_string(
        "components/product_colors.html", {"colors": colors}, request)
    response["product_colors_area"] = product_colors_area

    return JsonResponse(response)


@require_GET
@login_required
def remove_product_from_cart(request):
    # Get cart item.
    user = request.user
    item_id = request.GET.get("item_id")
    cart_item = CartItem.objects.filter(
        cart__is_paid=False, cart__user_id=user.id, id=item_id).first()

    # Remove item if exists.
    if cart_item is not None:
        cart_item.delete()
        cart = cart_item.cart
        response = {"text": "محصول با موفقیت از سبد خرید حذف شد",
                    "icon": "success", "position": "center",
                    "cart_total_discounted_price": cart.total_discounted_price(),
                    "cart_total_discounted": cart.total_discounted(),
                    "cart_total_price": cart.total_price()}
        return JsonResponse(response)

    # Return error.
    response = {"text": "محصول یافت نشد",
                "icon": "error", "position": "center"}
    return JsonResponse(response)

user_panel/views.py
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.views import View
from django.views.generic import UpdateView
from django.views.decorators.http import require_GET, require_POST
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.http import Http404, HttpResponse, JsonResponse
from django.contrib import messages
from django.core.paginator import (
    Paginator,
    PageNotAnInteger,
    EmptyPage
)

from account import models
from cart.models import Cart
from product.models import Product
from .models import UserProductList
from . import forms


@method_decorator(login_required, "dispatch")
class DashboardView(View):
    def get(self, request):
        context = {
            "user": request.user
        }
        return render(request, "user_panel/dashboard.html", context)


@method_decorator(login_required, "dispatch")
class EditProfileView(UpdateView):
    model = models.User
    form_class = forms.EditProfileForm
    template_name = "user_panel/edit_profile.html"
    success_url = reverse_lazy("user_panel:dashboard")

    def get_object(self, queryset=...):
        user = self.request.user
        return self.model.objects.get(is_active=True, id=user.id)

    def form_valid(self, form) -> HttpResponse:
        messages.success(self.request, "اطلاعات شما با موفقیت تغییر یافت")
        return super().form_valid(form)


@login_required
def change_password(request):
    if request.method == "GET":
        form = forms.ChangePasswordForm()
        return render(request, "user_panel/change_password.html", {"form": form})
    else:
        form = forms.ChangePasswordForm(request.POST)
        context = {
            "form": form
        }
        if form.is_valid():
            cd = form.cleaned_data
            user: models.User = request.user
            if user.check_password(cd["current_password"]):
                user.set_password(cd["password"])
                user.save()
                login(request, user)
                messages.success(request, "گذرواژه شما با موفقیت تغییر یافت")
                return redirect(reverse("user_panel:dashboard"))
            else:
                form.add_error("current_password", "گذرواژه نادرست است.")

        return render(request, "user_panel/change_password.html", context)


@require_GET
@login_required
def lists(request):
    """User lists page"""
    user = request.user
    lists = UserProductList.objects.filter(user=user)
    form = forms.UserProductListForm()

    context = {
        "lists": lists,
        "list_creation_form": form
    }

    return render(request, "user_panel/lists.html", context)


def base_product_list_filter(request, list_title):
    # Get user.
    user = request.user
    list = None
    if list_title == "لیست آرزو":
        # Get the user's wish list products.
        products = user.liked_products.all()
    else:
        list = get_object_or_404(UserProductList, user=user, title=list_title)
        products = list.products.all()

    # Paginate based on user selection.
    paginate_by = request.GET.get("paginate_by", "10")
    if paginate_by not in ["5", "10", "15"]:
        paginate_by = 10

    # Create the paginator object.
    paginator = Paginator(products, paginate_by)

    # Get the page number.
    page = request.GET.get("page", 1)

    # Get the selected page.
    try:
        page_obj = paginator.get_page(page)
    except PageNotAnInteger:
        page_obj = paginator.get_page(1)
    except EmptyPage:
        page_obj = paginator.get_page(paginator.num_pages)

    return page_obj, paginate_by, list


@require_GET
@login_required
def list_detail(request, list_title):
    page_obj, _, list = base_product_list_filter(request, list_title)
    edit_list_form = forms.UserProductListForm(instance=list)

    if not list:
        list = {
            "title": "لیست آرزو",
            "description": "محصولاتی که پسندیده بوده اید را می توانید در اینجا مشاهده کنید."
        }

    context = {
        "page_obj": page_obj,
        "edit_list_form": edit_list_form,
        "list": list
    }
    return render(request, "user_panel/list_detail.html", context)


@require_GET
@login_required
def products_list_filter(request) -> JsonResponse:
    """Filter the products of user list with ajax"""
    list_title = request.GET.get("list_name")
    page_obj, paginate_by, _ = base_product_list_filter(
        request, list_title)

    data = {}
    products_filter_url = reverse("user_panel:filter")
    if request.GET.get("paginate_change") == "true":
        data["paginates"] = render_to_string(
            "components/paginate.html", {"paginate_by": paginate_by, "products_filter_url": products_filter_url})
    data["products"] = render_to_string(
        "includes/products_partial.html", {"products": page_obj.object_list}, request)
    data["pagination"] = render_to_string(
        "components/paging.html", {"page_obj": page_obj, "products_filter_url": products_filter_url})

    return JsonResponse(data)


@require_POST
@login_required
def create_list(request) -> JsonResponse:
    """Create user list with ajax."""
    # Fill the list creation form.
    form = forms.UserProductListForm(request.POST)
    context = {}
    if form.is_valid():
        user = request.user
        list = form.save(commit=False)
        list.user = user
        # Is there a list for this user with the same title?
        if UserProductList.objects.filter(user=user, title=list.title).exists():
            form.add_error("title", "لیستی با این عنوان از قبل وجود دارد.")
            context["form"] = render_to_string(
                "components/list_creation_form.html", {"form": form})
        else:
            list.user = user
            # Save the list in database.
            list.save()
            lists = UserProductList.objects.filter(user=request.user)
            context["user_lists"] = render_to_string(
                "includes/lists_partial.html", {"lists": lists}, request)
    else:
        context["form"] = render_to_string(
            "components/list_creation_form.html", {"form": form})
    return JsonResponse(context)


@require_GET
@login_required
def edit_list(request):
    """Edit user lists with ajax."""
    try:
        list_id = int(request.GET.get("id"))
    except:
        response = {
            "text": "خطایی رخ داد",
            "icon": "error",
            "position": "center"
        }
        return JsonResponse(response)

    user = request.user
    # Find the current user list.
    list = get_object_or_404(UserProductList, id=list_id, user_id=user.id)
    current_list_title = list.title
    # Fill the edit list form.
    form = forms.UserProductListForm(request.GET, instance=list)
    context = {}
    if form.is_valid():
        new_list = form.save(commit=False)
        # If the title has changed, check its uniqueness.
        if new_list.title != current_list_title \
                and UserProductList.objects.filter(user=user, title=new_list.title).exists():
            form.add_error("title", "لیستی با این عنوان از قبل وجود دارد")
            context["form"] = render_to_string(
                "components/list_creation_form.html", {"form": form})
        else:
            # Save the changes in database.
            new_list.save()
    else:
        context["form"] = render_to_string(
            "components/list_creation_form.html", {"form": form})
    return JsonResponse(context)


@require_GET
@login_required
def remove_list(request) -> JsonResponse:
    """remove user list with ajax."""
    try:
        id = int(request.GET.get("id"))
    except:
        response = {
            "text": "خطایی رخ داد", "icon": "error", "position": "center"
        }
        return JsonResponse(response)
    # Find the user's selected list.
    list = UserProductList.objects.filter(
        user_id=request.user.id, id=id).first()
    # Return error if the list isn't found.
    if list is None:
        response = {
            "text": "لیست یافت نشد", "icon": "error", "position": "center"
        }
        return JsonResponse(response)

    # Delete the user list from the database.
    list.delete()

    response = {
        "text": "لیست حذف شد", "icon": "success", "position": "center"
    }
    return JsonResponse(response)


@require_GET
@login_required
def add_product_to_list(request) -> JsonResponse:
    """Add product to user list with ajax"""
    # Try to get the list id and product id.
    try:
        list_id = int(request.GET.get("list_id"))
        product_id = int(request.GET.get("product_id"))
    # Return error if the type of list id or product id is incorrect.
    except:
        response = {
            "text": "خطایی رخ داد",
            "icon": "error",
            "position": "center"
        }
        return JsonResponse(response)

    user = request.user

    # Get the products that this user can access.
    products = Product.access_controlled.filter_queryset_by_user_perms(user)

    # Find the selected product.
    product = products.filter(id=product_id).first()

    # Return error if product not found.
    if product is None:
        response = {
            "text": "محصول یافت نشد",
            "icon": "error",
            "positino": "center"
        }
        return JsonResponse(response)

    # Find the selected list.
    list = UserProductList.objects.filter(user=user, id=list_id).first()

    # Return error if list not found.
    if list is None:
        response = {
            "text": "لیست یافت نشد",
            "icon": "error",
            "positino": "center"
        }
        return JsonResponse(response)

    # Add product to list.
    list.products.add(product)

    response = {
        "text": "محصول با موفقیت به لیست شما اضافه شد",
        "icon": "success",

user_panel/templates/user_panel/cart.html
{% extends "shared/base.html" %}

{% load static poll_extras %}

{% block title %}
سبد خرید
{% endblock %}

{% block content %}

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>سبد خرید</h1>
                <nav class="d-flex align-items-center">
                    <a href="{% url 'home:index' %}">خانه<span class="lnr lnr-arrow-left"></span></a>
                    <a href="{% url 'user_panel:dashboard' %}">داشبورد<span class="lnr lnr-arrow-left"></span></a>
                    <a href="{% url 'user_panel:cart' %}">سبد خرید</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->

<!--================Cart Area =================-->
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-2 my-5">
            {% include "components/menu.html" %}
        </div>
        <div class="col-md-8 cart-area">
            <div class="container px-3 my-5 clearfix">
                <!-- Shopping cart table -->
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered m-0">
                            <thead>
                                <tr>
                                    <!-- Set columns width -->
                                    <th class="text-center align-middle py-3 px-0" style="width: 45px;">حذف؟</th>
                                    <th class="text-center py-3 px-4" style="width: 100px;">مجموع</th>
                                    <th class="text-center py-3 px-4" style="width: 120px;">تعداد</th>
                                    <th class="text-center py-3 px-4" style="width: 100px;">قیمت</th>
                                    <th class="text-center py-3 px-4" style="min-width: 400px;">محصول</th>
                                </tr>
                            </thead>
                            <tbody class="cart-items">
                                {% for item in cart.items.all %}
                                    {% with product=item.product %}
                                        <tr class="cart-item" id="cart-item-area-{{item.id}}">
                                            <!-- Delete Area -->
                                            <td class="text-center align-middle px-0">
                                                <a onclick="removeProductFromCart({{item.id}})"
                                                    class="shop-tooltip close float-none text-danger" title=""
                                                    data-original-title="Remove">
                                                    ×
                                                </a>
                                            </td>
                                            <!-- Total Price Area -->
                                            <td class="text-center font-weight-semibold align-middle p-4">
                                                <h6 id="cart-item-total-price-{{item.id}}">
                                                    {{item.total_price|separate}} (تومان)
                                                </h6>
                                            </td>
                                            <!-- Quantity Area -->
                                            <td class="align-middle p-4">
                                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                                    <div class="input-group-btn">
                                                        <button id="reduced-btn-{{item.id}}" class="btn btn-sm btn-warning" 
                                                            {% if item.quantity == 1 %}disabled="true"{% endif %}
                                                            onclick="
                                                                var result = document.getElementById('item-quantity-{{item.id}}');
                                                                var sst = result.value;
                                                                if( !isNaN( sst ) &amp;&amp; sst > 1 ) result.value--;
                                                                if( result.value == 1 ) document.getElementById('reduced-btn-{{item.id}}').disabled = true;
                                                                changeCartItemQuantity({{product.id}}, {{product.product.id}}, {{item.id}}, result.value);
                                                                return false;">
                                                            <i class="fa fa-minus"></i>
                                                        </button>
                                                    </div>
                                                    <input type="text" id="item-quantity-{{item.id}}"
                                                        class="form-control form-control-sm text-center"
                                                        value="{{item.quantity}}">
                                                    <div class="input-group-btn">
                                                        <button class="btn btn-sm btn-warning" onclick="
                                                                increaseProductQuantity('item-quantity-{{item.id}}', {{item.product.stock_count}});
                                                                var sst = document.getElementById('item-quantity-{{item.id}}').value;
                                                                var reducedBtn = document.getElementById('reduced-btn-{{item.id}}');
                                                                if( sst > 1 ) reducedBtn.disabled = false;
                                                                changeCartItemQuantity({{product.id}}, {{product.product.id}},{{item.id}}, sst);
                                                                ">
                                                            <i class="fa fa-plus"></i>
                                                        </button>
                                                    </div>
                                                </div>
                                            </td>
                                            <!-- Price Area -->
                                            <td class="text-center font-weight-semibold align-middle p-4 price">
                                                {% if product.final_price != product.get_price %}
                                                    <h6>{{product.final_price|separate}}</h6>
                                                    <h6 class="l-through">{{product.get_price|separate}}</h6>
                                                {% else %}
                                                    <h6>{{product.get_price|separate}}</h6>
                                                {% endif %}
                                                <h6>(تومان)</h6>
                                            </td>
                                            <!-- Product Area -->
                                            <td class="p-4">
                                                <div class="media align-items-center">
                                                    <div class="media-body text-right" dir="rtl">
                                                        <a href="{{product.get_absolute_url}}" class="d-block text-dark">
                                                            {{product.product.title}}
                                                        </a>
                                                        <small>
                                                            <span class="font-weight-bold">رنگ:</span>
                                                            <span class="ui-product-color ui-product-color-sm align-text-bottom"
                                                                title="{{product.color_name}}"
                                                                style="background:{{product.color_hex_code}};"></span> &nbsp;
                                                        </small>
                                                    </div>
                                                    <img src="{{ product.product.image.url }}"
                                                        class="d-block ui-w-40 ui-bordered mr-1 ml-2" alt="">
                                                </div>
                                            </td>
                                        </tr>
                                    {% endwith %}
                                {% empty %}
                                    <td colspan="5">
                                        <div class="alert alert-warning text-center" role="alert">
                                            <h4>
                                                هنوز محصولی اضافه نکردی.
                                                <a href="{% url 'product:list' %}">بریم اضافه کنیم</a>
                                            </h4>
                                        </div>
                                    </td>
                                {% endfor %}
                                
                            </tbody>
                        </table>
                    </div>
                    <!-- / Shopping cart table -->
                    <div class="pb-4" dir="rtl">
                        <div class="col-md-7 text-center justify-content-center d-flex pb-4 border">
                            <div class="mt-4 mr-5">
                                <strong>قیمت اولیه</strong>
                                <div class="text-large">
                                    <strong id="cart-total-price">{{cart.total_price|separate}} (تومان)</strong>
                                </div>
                            </div>
                            <div class="mt-4 mr-5">
                                <strong>تخفیف</strong>
                                <div class="text-large">
                                    <strong id="cart-total-discounted">{{cart.total_discounted|separate}} (تومان)</strong>
                                </div>
                            </div>
                            <div class="mt-4 mr-5">
                                <strong>قیمت بعد از تخفیف</strong>
                                <div class="text-large">
                                    <strong id="cart-total-discounted-price">{{cart.total_discounted_price|separate}} (تومان)</strong>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="float-right">
                        <a href="{% url 'product:list' %}">
                            <button type="button" class="btn btn-lg btn-default md-btn-flat mt-2 mr-3">
                                برگردیم به صفحه محصولات
                            </button>
                        </a>
                        <button type="button" class="btn btn-lg btn-primary mt-2">
                            تکمیل فرایند خرید
                        </button>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<!--================End Cart Area =================-->

{% endblock %}

user_panel/templates/user_panel/edit_profile.html
{% extends "shared/base.html" %}

{% block title %}
    ویرایش اطلاعات
{% endblock %}

{% block content %}

<!-- start banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>ویرایش اطلاعات</h1>
                <nav class="d-flex align-items-center">
                    <a href="{% url 'home:index' %}">خانه<span class="lnr lnr-arrow-left"></span></a>
                    <a href="{% url 'user_panel:dashboard' %}">داشبورد<span class="lnr lnr-arrow-left"></span></a>
                    <a href="{% url 'user_panel:edit_profile' %}">ویرایش اطلاعات</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->

<section class="section_gap">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                {% include "components/menu.html" %}
            </div>
            <div class="col-md-8">
                <div class="form-control login-form" dir="rtl">
                    <div class="text-center">
                        <h3>ویرایش اطلاعات</h3>
                    </div>
                    <form class="login_form text-right" method="post" enctype="multipart/form-data" id="contactForm" novalidate="novalidate">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="col-md-12 form-group">
                                {{ field.errors }}
                                {{ field.label }}
                                {{ field }}
                            </div>
                        {% endfor %}
                        <div class=" col-md-6 form-group container">
                            <button type="submit" value="submit" class="primary-btn">ویرایش</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}