account/urls.py
from django.urls import path

from .views import (
    RegisterView,
    ActivateAccountView,
    LoginView,
    LogoutView,
    ForgetPasswordView,
    ResetPasswordView,
)

app_name = "account"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("activate-account/<str:email_activate_code>/", ActivateAccountView.as_view(), name="activate_account"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("forget-password", ForgetPasswordView.as_view(), name="forget_password"),
    path("reset-password/<str:activate_code>/", ResetPasswordView.as_view(), name="reset_password"),
]

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("add-product-to-cart/", views.add_product_to_cart,
         name="add_product_to_cart"),
    path("remove-product-from-cart/", views.remove_product_from_cart,
         name="remove_product_from_cart"),
]

contact_us/urls.py
from django.urls import path
from .views import ContactUsView

app_name = "contact_us"

urlpatterns = [
    path("", ContactUsView.as_view(), name="contact_us")
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index")
]

product/urls.py
from django.urls import path, re_path

from product.views import (
    product_list,
    product_list_filter,
    ProductDetailView,
    like_product,
    remove_comment,
    change_comment_status,
)

app_name = "product"

urlpatterns = [
    path("", product_list, name="list"),
    path("filter/", product_list_filter, name="filter"),
    path("like-product/", like_product, name="like_product"),
    path("remove-comment/", remove_comment, name="remove_coment"),
    path("change-comment-status/", change_comment_status, name="change_comment-status"),
    re_path(r"(?P<slug>[-\w0-9]+)/$", ProductDetailView.as_view(), name="detail"),
]

shop_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('account.urls')),
    path('products/', include('product.urls')),
    path('user/', include('user_panel.urls')),
    path('cart/', include('cart.urls')),
    path('contact-us/', include('contact_us.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/footer.html
{% load static %}

<footer class="footer-area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>About Us</h6>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt
                        ut labore dolore
                        magna aliqua.
                    </p>
                </div>
            </div>
            <div class="col-lg-4  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Newsletter</h6>
                    <p>Stay update with our latest</p>
                    <div class="" id="mc_embed_signup">

                        <form target="_blank" novalidate="true"
                            action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                            method="get" class="form-inline">

                            <div class="d-flex flex-row">

                                <input class="form-control" name="EMAIL" placeholder="Enter Email"
                                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '"
                                    required="" type="email">


                                <button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right"
                                        aria-hidden="true"></i></button>
                                <div style="position: absolute; left: -5000px;">
                                    <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value=""
                                        type="text">
                                </div>

                                <!-- <div class="col-lg-4 col-md-4">
                                            <button class="bb-btn btn"><span class="lnr lnr-arrow-right"></span></button>
                                        </div>  -->
                            </div>
                            <div class="info"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget mail-chimp">
                    <h6 class="mb-20">Instragram Feed</h6>
                    <ul class="instafeed d-flex flex-wrap">
                        <li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Follow Us</h6>
                    <p>Let us be social</p>
                    <div class="footer-social d-flex align-items-center">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-behance"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
            <p class="footer-text m-0">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;
                <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is
                made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com"
                    target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
        </div>
    </div>
</footer>

templates/components/header.html
{% load static %}

<header class="header_area sticky-header">
    <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light main_box">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <a class="navbar-brand logo_h" href="{% url "home:index" %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    <ul class="nav navbar-nav menu_nav ml-auto">
                        <li class="nav-item {% if request.resolver_match.url_name == "index" %}active{% endif %}">
                            <a class="nav-link" href="{% url 'home:index' %}">خانه</a>
                        </li>
                        <li class="nav-item submenu dropdown {% if request.resolver_match.app_name == "product" %}active{% endif %}">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                                aria-haspopup="true" aria-expanded="false">خرید</a>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a class="nav-link" href="{% url 'product:list' %}">محصولات</a></li>
                                <li class="nav-item"><a class="nav-link" href="checkout.html">پرداخت</a></li>
                            </ul>
                        </li>
                        <li class="nav-item submenu dropdown {% if request.resolver_match.app_name == "account" %}active{% endif %}">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                            aria-haspopup="true" aria-expanded="false">صفحات</a>
                            <ul class="dropdown-menu">
                                {% if request.user.is_authenticated %}
                                    <li class="nav-item"><a class="nav-link" onclick="logoutAlert('{% url 'account:logout' %}')">خروج</a></li>
                                {% else %}
                                    <li class="nav-item"><a class="nav-link" href="{% url 'account:login' %}">ورود</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{% url 'account:register' %}">ثبت نام</a></li>
                                {% endif %}
                                <li class="nav-item"><a class="nav-link" href="tracking.html">پیگیری</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                                aria-haspopup="true" aria-expanded="false">وبلاگ</a>
                        </li>
                        <li class="nav-item {% if request.resolver_match.app_name == "contact_us" %}active{% endif %}">
                            <a class="nav-link" href="{% url 'contact_us:contact_us' %}">
                                تماس با ما
                            </a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if request.user.is_superuser %}
                            <li class="nav-item">
                                <a href="/admin">
                                    <span>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                                            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                                        </svg>
                                    </span>
                                <a>
                            </li>
                        {% endif %}
                        {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a href="{% url "user_panel:dashboard" %}">
                                    <span>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                                            <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z"/>
                                        </svg>
                                    </span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'user_panel:cart' %}" class="cart">
                                    <span class="ti-bag"></span>
                                </a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <button class="search"><span class="lnr lnr-magnifier" id="search"></span></button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="search_input" id="search_input_box" dir="rtl">
        <div class="container">
            <form class="d-flex justify-content-between" action="{% url 'product:list' %}">
                <input type="text" class="form-control" id="search_input" name="q" value="{{request.GET.q}}" placeholder="اینجا سرچ کنید">
                <button type="submit" class="btn"></button>
                <span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
            </form>
        </div>
    </div>
</header>